services:
  - type: web
    name: rentcar-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false  # This will be set manually in the Render dashboard
      - key: JWT_SECRET
        sync: false  # This will be set manually in the Render dashboard
    autoDeploy: true
